pythonclub/pythonclub.github.io

content/gerenciando-banco-dados-sqlite3-python-parte2.rst

https no clone do github em
http://pythonclub.com.br/gerenciando-banco-dados-sqlite3-python-parte2.html

https no clone do github

---

content/entrevista_henrique_bastos.md

Uma entrevista curta com Henrique Bastos que fiz inicialmente para o meu blog pessoal, mas estou migrando o conteúdo de Python para o PythonClub

Uma entrevista Henrique Bastos

---

content/six.md

possivel solução provisória para https://github.com/pythonclub/pythonclub.github.io/issues/189

retirada tag python3

---

content/debugging-em-python-sem-ide.md
content/publicando_seu_hello_world_no_heroku.md
content/testes_de_carga_com_o_locust.md

Dei uma revisada no PT dos meus posts.

correções nos post do autor Diego Garcia

---

content/postgresql-django.rst
content/postgresql-python3.rst
content/tutorial-postgresql.rst

revisão final de links

---

theme/templates/base.html

meta para deixar a cor da barra de endereço personalizada no chorme do android, seguindo a onda do material design

theme color for chrome in mobile

---

content/django_releases_em_10_minutos.rst

Um overview básico sobre as features que foram lançadas nos últimos 3 anos.

Django - 3 anos em 10 minutos.

---

content/n_a_1_em_20_minutos.rst

Publicação da minha palestra realizada no Luizalabs no dia 08/05.

Publicação - De N a 1 em 20 minutos

---

content/desenvolvendo-para-google-app-engine-com-tekton.md

Meu primeiro artigo para o PythonClub.
Alguém pode revisar por favor?
Espero que gostem. :)

Artigo: Desevolvendo para o GAE com Tekton

---

content/n_a_1_em_20_minutos.rst

Incorporando o prof Pasquale :)

Correção erros ortográficos

---

content/a-armadilha-dos-argumentos-com-valores-padrao.md

Complementei o post com uma sugestão do @rochacbruno

improve post "a armadilha dos argumentos..."

---

content/raspando-a-web-com-python-parte-1.md

Breve tutorialzinho de como raspar dados de um XML com Python puro (sem dependências externas).
Vai ser continuado com outros artigos incluindo dependências externas (lxml, cssselect, scrapy).

Artigo sobre raspar dados com python

---

content/class-based-views-no-django.md

@rochacbruno, @luzfcb, @igr-santos e @LucasMagnum se algum de vocês puder revisar o texto eu ficaria grato.
Abraços.

Adiciona texto sobre CBV's no Django

---

content/class-based-views-no-django.md
content/django_na_pratica_parte_1.rst

Só corrigindo algumas ortografias :)

Professor Pasquali :)

---

content/material-do-tutorial-web-scraping-na-nuvem.md

Olá!
O @erichideki me encorajou a mandar o material do tutorial de web scraping que apresentei na Python Brasil semana passada, então aqui vai. :)
Looks good?
Valeu!

Adiciona material do tutorial de web scraping apresentado na #pybr11

---

content/material-do-tutorial-web-scraping-na-nuvem.md

Ajustes conforme comentários da revisão em #227.

Ajustando titulo e metadata

---

content/what_the_flask_flask_patterns.md

Adicionando link para parte 3 do What The Flask

---

.gitignore
content/diferenca-operadores.md

Coloquei um post, mais para uma dica/curiosidade sobre operadores python, que repliquei do meu blog.
E também coloquei no .gitignore para ignorar a pasta "venv", comum onde a galera coloca o outrput do virtualenv.

New post: Diferença entre == e is

---

content/criando-novos-comandos-no-django-admin.md

Arrumando links e indentação

---

content/criando-novos-comandos-no-django-admin.md

Atualizei alguns comandos no post.

Atualizando post

---

.gitignore
content/python-com-unittest-travis-e-coveralls-parte-1-de-4.md

Minha primeira postagem pessoal. Espero que gostem!

[NEW] Python com Unittest, Travis CI, Coveralls e Landscape (Parte 1 de 4)

---

content/python-com-unittest-travis-ci-coveralls-e-landscape-parte-3-de-4.md
content/python-com-unittest-travis-ci-coveralls-e-landscape-parte-4-de-4.md
content/python-com-unittest-travis-e-coveralls-parte-1-de-4.md
content/python-com-unittest-travis-e-coveralls-parte-2-de-4.md

* Atualizei as postagens com o novo domínio do meu blog.

[FIX] Atualizado endereco do site do autor

---

content/curso-asyncio-aula00.rst

Primeiro vídeo da série sobre asyncio.

Curso asyncio - Aula 00

---

content/tdd-com-python-e-flask.md

Fix wrong variable name in the TDD with Flask tutorial

---

content/bot-telegram-e-web-scraping.md
content/bot-telegram-e-web-scrpagin.md

Adicionada primeira parte do artigo.

add primeira parte do artigo.

---

content/abrangencia-de-listas-e-dicionarios.md

* Post original: http://codigoavulso.com.br/abrangencia-de-listas-e-dicionarios.html

[NEW] Tutorial sobre abrangência de listas e dicionários com Python

---

content/abrangencia-de-listas-e-dicionarios.md

palavra resolver esta grafada errada.

Pequena correção de ortografia, em 15/02/2017

---

content/configurando-python-3.5-openshift.md

Fiz um post de como configurar o openshift utilizando um cartridge customizado para poder utilizar o python3.5, já que não existe um cartridge oficial.
Espero que ajude o pessoal.

Adicionando post sobre como configurar o openshift + flask + gunicorn com python 3.5

---

content/configurando-python-3.5-openshift.md

Correção em tag que o markdown estava escondendo e precisava ser escapado.

Atualizando e deixando <app-name> visivel

---

content/peewee-um-orm-python-minimalista.md

Novo artigo: Peewee um ORM Python minimalista

---

content/programacao-funcional-com-python-2.md

Terceira parte sobre a série de programação funcional.

Programação funcional #2 iteraveis e iteradores

---

content/upload-de-arquivos-com-socket-e-struct.md

Enviando tutorial sobre como usar socket e struct pra enviar arquivos para servidores.
Desde já, deixando claro que aceito a publicação em Creative Commons.

Add upload arquivo socket struct

---

content/upload-de-arquivos-com-socket-e-struct.md

Lendo o artigo, percebi alguns acentos faltando, e fiz uma breve correção.

pequenas correções ortográficas

---

content/operadores_ternarios.md

Explicação breve sobre o uso do recurso no python com alguns exemplos em código.

Publicação sobre operadores ternários (ou expressões condicionais).

---

content/abrangencia-de-listas-e-dicionarios.md
content/como-distribuir-seu-projeto-python-com-pypi.md
content/gerando-relatorios-de-teste-com-coveralls.md
content/peewee-um-orm-python-minimalista.md
content/python-com-unittest-travis-ci-coveralls-e-landscape-parte-3-de-4.md
content/python-com-unittest-travis-ci-coveralls-e-landscape-parte-4-de-4.md
content/python-com-unittest-travis-e-coveralls-parte-1-de-4.md
content/python-com-unittest-travis-e-coveralls-parte-2-de-4.md

Alguns dados e informações dos meus posts estão desatualizados ou com erros de digitação. Este PR atualiza essas informações! :grin:

Atualiza dados dos meus posts

---

content/encapsulamento-da-logica-do-algoritmo.md

Segue um artigo que eu escrevi para publicação.

Artigo: Encapsulamento da lógica do algoritmo

---

content/funcao-inplace-ou-copia-de-valor.md

Segue outro artigo que escrevi para publicação.

Artigo: Funções in place ou cópia de valor

---

content/oo-de-outra-forma-6.md

Finalizando a série sobre outra perspectiva de orientação a objetos em Python.

Adiciona artigo: Orientação a objetos de outra forma: Property
